### PR TITLE
Convert some already generic things to GenericAlias to be consistent

### PR DESCRIPTION
**Pull request by emmatyping**
These were made generic by @isidentical. I kept the tests, but I can also delete them if you prefer (or add them to test_genericalias I guess)

### CODE REVIEW

**Comment by gvanrossum** [comment]
On macOS I get two test failures when running `test_os`:
```
======================================================================
FAIL: test_pathlike_class_getitem (test.test_os.TestPEP519)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/guido/pep585/Lib/test/test_os.py", line 4083, in test_pathlike_class_getitem
    self.assertIs(os.PathLike[bytes], os.PathLike)
AssertionError: os.PathLike[bytes] is not <class 'os.PathLike'>

======================================================================
FAIL: test_pathlike_class_getitem (test.test_os.TestPEP519PurePython)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/guido/pep585/Lib/test/test_os.py", line 4083, in test_pathlike_class_getitem
    self.assertIs(os.PathLike[bytes], os.PathLike)
AssertionError: os.PathLike[bytes] is not <class 'os.PathLike'>
```
(I realize that one weakness of my setup for this branch is that CI doesn't run for PRs.)

**Comment by emmatyping** [comment]
>(I realize that one weakness of my setup for this branch is that CI doesn't run for PRs.)

Yeah :(

I ran test_os, but I kept getting debug assertion failures, which perhaps I should report.

**Comment by gvanrossum** [comment]
Looking to repro that. Presumably the failures don't occur on master?

**Comment by gvanrossum** [comment]
Hm, I ran `./configure --with-pydebug`, `make clean`, `make -k -j` and then re-ran test_os, but no faults. So maybe Windows only?

**Comment by emmatyping** [comment]
I haven't checked master, I was going to do that next, I think it is a Windows issue that we haven't caused.

**Comment by emmatyping** [comment]
Just checked master and the failures are on master. To b.p.o!

**Comment by gvanrossum** [comment]
Huh, I still get the same failures?

**Comment by emmatyping** [comment]
D'oh! I need to test it is a GenericAlias, sorry.

**Pull request merged**
